common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost

development:
  <<: *common
  database: edinburgh-scrapbooks-development

test:
  <<: *common
  database: edinburgh-scrapbooks-test

production:
  <<: *common
  database: edinburgh-scrapbooks-production
