common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost

development:
  <<: *common
  database: edinburgh-collected-development

test:
  <<: *common
  database: edinburgh-collected-test

production:
  <<: *common
  database: <production db name here>
